swagger.enabled=true
file.uploadFolder=D://uploadFile
file.staticAccessPath=D://uploadFile

spring.profiles.active=dev
server.port=8080
server.servlet.context-path=/

spring.devtools.restart.enabled=false
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**

#模板引擎配置
#suffix: .html  默认后缀
#prefix: classpath:/templates/  默认前缀
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.mvc.static-path-pattern=/static/**
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

spring.aop.proxy-target-class=true

logging.level.root=info
logging.file.path=./logs

#http encoding
spring.banner.charset=UTF-8
spring.messages.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
#\u6587\u4ef6\u5927\u5c0f
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB
#converters \u9ed8\u8ba4jackson
spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss.SSS
spring.jackson.default-property-inclusion=non-null
spring.mvc.format.date=yyyy-MM-dd HH:mm:ss.SSS


